const level1 = new Level([
    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 0),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 0),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 0),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 0),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 0),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719),

    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 719 * 2),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 719 * 2),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 719 * 2),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 719 * 2),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 719 * 2),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719 * 3),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719 * 3),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719 * 3),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719 * 3),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719 * 3),

    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 719 * 4),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 719 * 4),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 719 * 4),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 719 * 4),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 719 * 4),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719 * 5),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719 * 5),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719 * 5),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719 * 5),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719 * 5),

    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 719 * 6),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 719 * 6),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 719 * 6),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 719 * 6),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 719 * 6),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719 * 7),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719 * 7),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719 * 7),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719 * 7),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719 * 7),

    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 719 * 8),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 719 * 8),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 719 * 8),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 719 * 8),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 719 * 8),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719 * 9),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719 * 9),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719 * 9),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719 * 9),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719 * 9),

    new BackgroungObject('img/3. Background/Layers/5. Water/D1.png', 719 * 10),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D1.png', 719 * 10),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D1.png', 719 * 10),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D1.png', 719 * 10),
    new BackgroungObject('img/3. Background/Layers/1. Light/1.png', 719 * 10),

    new BackgroungObject('img/3. Background/Layers/5. Water/D2.png', 719 * 11),
    new BackgroungObject('img/3. Background/Layers/3.Fondo 1/D2.png', 719 * 11),
    new BackgroungObject('img/3. Background/Layers/4.Fondo 2/D2.png', 719 * 11),
    new BackgroungObject('img/3. Background/Layers/2. Floor/D2.png', 719 * 11),
    new BackgroungObject('img/3. Background/Layers/1. Light/2.png', 719 * 11),
], [
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Fish(),
    new Finalboss(),
],
);